[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"


[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",

  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]

[env]
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" } # save disk space and download time
